version: '3'

services:
  youphptube:
#    image: YouPHPTube
    build: ./YouPHPTube
    container_name: youphptube
    restart: always
    ports:
      - 80:8000
    volumes:
      - ./YouPHPTube/videos:/var/www/html/videos
    networks:
      local:
        ipv4_address: 192.168.1.3

  youphptubeen:
#    image: YouPHPTubeen
    build: ./YouPHPTubeen
    container_name: youphptubeen
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./YouPHPTubeen/videos:/var/www/html/videos
    networks:
      local:
        ipv4_address: 192.168.1.4

  mysql:
    image: mysql
    build: ./mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysql:/var/lib/mysql
    networks:
      local:
        ipv4_address: 192.168.1.2
    environment:
      TZ: Asia/Tokyo


# docker network create --driver="bridge" --subnet=192.168.1.0/24 local
networks:                   
  local:                    
    external:                 
      name: local
  
